# Generated by Django 4.1.2 on 2022-11-15 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('logo_img', models.ImageField(upload_to='photos/logo/%Y/%m/%d/')),
                ('url', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
