# Generated by Django 4.1.2 on 2022-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to='photos/logo/%Y/%m/%d/'),
        ),
    ]
