# Generated by Django 4.1.2 on 2022-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='/', max_length=200, unique=True),
        ),
    ]
