# Generated by Django 4.1.2 on 2022-11-20 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('logo_img', models.ImageField(blank=True, upload_to='photos/logo/%Y/%m/%d/')),
                ('url', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=150)),
                ('nav_title', models.CharField(default='', max_length=50)),
                ('list_order', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=False)),
                ('has_title', models.BooleanField(default=False)),
            ],
        ),
    ]
