# Generated by Django 4.1.2 on 2022-11-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='has_title',
            field=models.BooleanField(default=False),
        ),
    ]
